// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPNtalxbE-yCrIc22i9_lpqmArtPp0QcU',
    appId: '1:50990686764:web:0e37b0eb1d59ea3e59a789',
    messagingSenderId: '50990686764',
    projectId: 'ecom-89b8f',
    authDomain: 'ecom-89b8f.firebaseapp.com',
    storageBucket: 'ecom-89b8f.firebasestorage.app',
    measurementId: 'G-H2FDSP2W1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnw5Rhiiuhlxw6YDCmzoLYC5hshxlPEPk',
    appId: '1:50990686764:android:5b7cf3a07fb3843359a789',
    messagingSenderId: '50990686764',
    projectId: 'ecom-89b8f',
    storageBucket: 'ecom-89b8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj63ChagvGJ-fO-IZuBaC2Zqr2hqnKp54',
    appId: '1:50990686764:ios:2e8944cdade56a2059a789',
    messagingSenderId: '50990686764',
    projectId: 'ecom-89b8f',
    storageBucket: 'ecom-89b8f.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPNtalxbE-yCrIc22i9_lpqmArtPp0QcU',
    appId: '1:50990686764:web:4a50c89e3aae61ad59a789',
    messagingSenderId: '50990686764',
    projectId: 'ecom-89b8f',
    authDomain: 'ecom-89b8f.firebaseapp.com',
    storageBucket: 'ecom-89b8f.firebasestorage.app',
    measurementId: 'G-BRQJYSQKM0',
  );

}